In [36]:
import os
import json
import requests
import pandas as pd
import numpy as np
import re
import random
import time

In [25]:
start = 1  # inclusive
end = 100  # exclusive
number_of_integers = 10

# Generate the list
unique_integers = random.sample(range(start, end), number_of_integers)

print(unique_integers)

[99, 5, 10, 32, 81, 86, 28, 68, 40, 26]

In [14]:
token = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhMTMxYTQ1My1hM2IyLTQwMTUtODQ2Ny05MzAyZjk3MTFkOGEifQ.eyJpYXQiOjE3MjExMTQ5NTAsImp0aSI6IjE4MDk3NmQyLTQ5MTktNDQxNC05ZjU3LTFmMDlhOTdmOGIyMCIsImlzcyI6Imh0dHBzOi8vYXV0aC5zb2Z0d2FyZWhlcml0YWdlLm9yZy9hdXRoL3JlYWxtcy9Tb2Z0d2FyZUhlcml0YWdlIiwiYXVkIjoiaHR0cHM6Ly9hdXRoLnNvZnR3YXJlaGVyaXRhZ2Uub3JnL2F1dGgvcmVhbG1zL1NvZnR3YXJlSGVyaXRhZ2UiLCJzdWIiOiIzNGUyMTU5Yi1lOGEyLTQ5ODItODZiYy1kM2VhYzU5Y2EyYzAiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoic3doLXdlYiIsInNlc3Npb25fc3RhdGUiOiI1NmY2MTViNi00OWRmLTQwYzktYWY0OS1jOTU0MDM4NjU0MjciLCJzY29wZSI6Im9wZW5pZCBvZmZsaW5lX2FjY2VzcyBwcm9maWxlIGVtYWlsIn0.p_P9aSAVDb4Zgb8_1_4d9sGwHD4WQRDVgbBXJSDaSC0"
headers = {
    "Authorization": f"Bearer {token}"
}
prefix = "https://archive.softwareheritage.org/api/1/revision/"
prefix_file = "/home/infres/rapaport/results/FULL/focus/classes"
pattern = r".*swh:1:rev:([a-f0-9]{40})"
class_files = os.listdir(prefix_file)
df = pd.DataFrame()
for file in class_files:
    df = pd.concat([df, pd.read_csv(prefix_file + "/" + file, delimiter=";")])
df['sub_categ_clean'] = list(map(lambda categ: categ.strip("{}").split(", "), df["sub_categories"]))
df

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories,sub_categ_clean
0,https://github.com/kohkimakimoto/xssh,swh:1:snp:65ff469dd22aeb071a75d563327468616484...,refs/heads/master,swh:1:rev:2868df901ea623114abea4cbfbfcfe190ccb...,swh:1:snp:cf9f639cf4b85143fb1b894c86d30e078029...,"Some(""swh:1:rev:2868df901ea623114abea4cbfbfcfe...",DIR,{DifferentBranchName},[DifferentBranchName]
1,https://github.com/krisp1/krisp1.github.io,swh:1:snp:f3e8381f70da6ecc4d114626d0f5def6806d...,refs/heads/master,swh:1:rev:485eed8fb5e62363c91b2cf316e891356b44...,swh:1:snp:b762ef168fd630747edc2fbbc5992a297a6a...,NaN,DIR,"{ContentModified, ContentRemoved}","[ContentModified, ContentRemoved]"
2,https://github.com/kyrogon/kyrogon.github.io,swh:1:snp:bbf31fc5c24511e3b1f278c2bd6c02daf300...,refs/heads/master,swh:1:rev:c31f2c35149fa444d8ac81e674048981b5d3...,swh:1:snp:89b505da7fbb21ce8483cac7ae79e3ba1cdc...,NaN,DIR,{ContentModified},[ContentModified]
3,https://github.com/kzz710/kzz710.github.io,swh:1:snp:4a1e274c4f0d5963633dc70514d1f417524f...,refs/heads/master,swh:1:rev:0f3cc235c1813bef907b41c7931695757080...,swh:1:snp:1644a8746b384c7f6c0b7b8403671641fce1...,"Some(""swh:1:rev:edbfd32620710988987ff1e852b8b0...",META,"{Author, Committer, Date, CommitterDate}","[Author, Committer, Date, CommitterDate]"
4,https://github.com/kofemann/linux-redpatch,swh:1:snp:0d6de0f9d91cb6cd430b466e8fc8f9055210...,refs/heads/master,swh:1:rev:78eb00cc574d3dbf8e6bed804948a89e8110...,swh:1:snp:a739e574b976565f0fccbe896041a0fcb34c...,"Some(""swh:1:rev:78eb00cc574d3dbf8e6bed804948a8...",DIR,{DifferentBranchName},[DifferentBranchName]
...,...,...,...,...,...,...,...,...,...
13850,https://github.com/dongnengyu/dongnengyu.githu...,swh:1:snp:ad27818dac12e27b942410052b4b2b8c840e...,refs/heads/master,swh:1:rev:c6c9a851c8513ac26c7be845347efd3b64a4...,swh:1:snp:d204d7610661f2ec37589142e7874fab68eb...,NaN,DIR,{ContentModified},[ContentModified]
13851,https://github.com/dibsonmuad/acad,swh:1:snp:b4b9daa4d349b4a340ed9d863cd03b6df451...,refs/heads/master,swh:1:rev:8a1c752017d49c72f73912eccb1dbf501169...,swh:1:snp:5a4edbe02a9fca00f7980b7f3f9add3b4fef...,"Some(""swh:1:rev:47f5e1c9d5e64f2d8fa0ce6fc8a805...",META,{Committer},[Committer]
13852,https://github.com/dnhansen/dnhansen.github.io,swh:1:snp:0779205db215cf4024a7c387aecf6f193ea9...,refs/heads/master,swh:1:rev:eedf56dcd710025fedaeddae589fc95af8ef...,swh:1:snp:7c83a150f9afadcb431c20405b9c0f5bd520...,NaN,DIR,{ContentRemoved},[ContentRemoved]
13853,https://github.com/dotnet/maui,swh:1:snp:9dec8ee55e6256e1c72b9042282f61808e4f...,refs/heads/dev/jd/collectionviewfoot,swh:1:rev:31521da438318317af8032503791fcf9340d...,swh:1:snp:b619b9dd8e5c4b7abd5ed2464a2879e58fa9...,NaN,DIR,{ContentModified},[ContentModified]
13854,https://github.com/doriclazar/Profiler,swh:1:snp:adc80747cc252f68a71045bf31f649041c45...,refs/heads/master,swh:1:rev:83386f2211cf48c73b04be9c20e13a367648...,swh:1:snp:9e038ed4608ef3accf5bfbd2c2ab21105443...,NaN,DIR,"{ContentModified, ContentRemoved}","[ContentModified, ContentRemoved]"

In [28]:
others = df[df['sub_categ_clean'].apply(lambda x: '' in x)]
others

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories,sub_categ_clean
452,https://github.com/ldericher/fftcgtool,swh:1:snp:5512da3c5eaf5492dadf7996c3c9f9e4ff0a...,refs/heads/master,swh:1:rev:630177ae68501c3ed6f125c097af12402efc...,swh:1:snp:e73218be6d320ece571c809e123d4f5385b7...,"Some(""swh:1:rev:cf1b947d3268372107db02c6044304...",META,{},[]
649,https://github.com/kloktech/recover_lost_mac,swh:1:snp:e4bf3c670c39d0849181b37cde5bd1840768...,refs/heads/master,swh:1:rev:032b30e9e780531d64400b53d008dcf7d524...,swh:1:snp:92112015dcd4058e352b1ac21c9015758f04...,"Some(""swh:1:rev:891def9ca705e80be40af2d50c8499...",META,{},[]
707,https://github.com/lauraestevens/lauraestevens...,swh:1:snp:9b72421a798d83e7103f4c087c93513b7e14...,refs/heads/master,swh:1:rev:1749d929e836682aa34da9203d95813ef1a3...,swh:1:snp:e57a3cae18da3f49c0f3c3e1e55f2c03f568...,"Some(""swh:1:rev:0179c2d82e68c8558c797dea43ae10...",META,{},[]
946,https://github.com/koselig/koselig,swh:1:snp:30b634b8a7fc5f3db63f2020938061062802...,refs/heads/master,swh:1:rev:8f90585581fba29190c17701f014327fb8d1...,swh:1:snp:61387cde0db0b6d642ceaeb9789cbc3568b2...,"Some(""swh:1:rev:920274facf7268c8c636a37e04124a...",META,{},[]
1022,https://github.com/ksekimoto/micropython,swh:1:snp:5163aa8674c2508ba0e2fea52599710ccb44...,refs/heads/master,swh:1:rev:39799f7564d28737fa815a3a5d370c914149...,swh:1:snp:8a2b17f72ee101471c362f41dda1fc483c59...,"Some(""swh:1:rev:1162b22e7eb84a4329d9d655512e90...",META,{},[]
...,...,...,...,...,...,...,...,...,...
13297,https://github.com/douggie/XChange,swh:1:snp:6e0d1839bb5392d632f61a37010c5fadad59...,refs/heads/develop,swh:1:rev:aec863d8196d88df66716c490bba1b205dec...,swh:1:snp:4bd844d84b1837b81075e14ed49c1ad5cd08...,"Some(""swh:1:rev:8d72204c44b5a52df96883116eb641...",META,{},[]
13354,https://github.com/dhlk/woolddons,swh:1:snp:a5b927c404590b6d1629b9a8251b8ce1f718...,refs/heads/master,swh:1:rev:b9270f37af9099447b978099c78125ff76f5...,swh:1:snp:5fd9d8408f353b26eed60bc676d8c7abd687...,"Some(""swh:1:rev:681ed65e4ddb9d0d33246bfa52ab5d...",META,{},[]
13376,https://github.com/drewbailey/nomad-dev,swh:1:snp:45962de5e41fcd34b3d48c121bd0e3d2009b...,refs/heads/master,swh:1:rev:a70e24c2d4cd33e8bd40cba27043a7f1022a...,swh:1:snp:e1ee4bb997620cb7ad8d1cda7dacd349f856...,"Some(""swh:1:rev:366dc3a486e9b15cfea31f6992e942...",META,{},[]
13385,https://github.com/dikiaap/dotfiles,swh:1:snp:10ed59a86598eb6b085f690c49c92b6cc9d3...,refs/heads/master,swh:1:rev:b4f74f5399201068c61467429b47cdd4aa6e...,swh:1:snp:a85df7acd2ce09bef7d883b01b70842a4759...,"Some(""swh:1:rev:5cd4336696c0a9122ab7db1c9d0e5b...",META,{},[]
13813,https://github.com/dma-isoc/notredam,swh:1:snp:a66872eb2c6ffee3fca3a611d36a9e566906...,refs/heads/master,swh:1:rev:67fb1fd776b5d369763b1dee83d6fcfb9215...,swh:1:snp:4a95032eff1f260e278aee3206046cb19f19...,"Some(""swh:1:rev:2a02df4f4652e12ffccd8ecbd51a86...",META,{},[]

In [37]:
diff = {}
cpt = 0
for mc in others['missing_commit']:
    cpt += 1
    filter = others[others['missing_commit'] == mc]
    for fd in filter['first_difference']:
        match_mc = re.search(pattern, mc)
        if match_mc:
            extracted_hash_mc = match_mc.group(1)
            #print(extracted_hash_mc)
        else:
            print("No match found")
        match_fd = re.search(pattern, fd)
        if match_fd:
            extracted_hash_fd = match_fd.group(1)
            #print(extracted_hash_fd)
        else:
            print("No match found")
        resp_mc = requests.get(prefix + extracted_hash_mc, headers=headers).json()
        resp_fd = requests.get(prefix + extracted_hash_fd, headers=headers).json()
        for field in resp_mc:
            if field == 'url' or field == 'history_url' or field == 'id':
                continue
            if resp_mc[field] != resp_fd[field]:
                diff.setdefault(field, [])
                diff[field].append(((resp_mc['id'], resp_mc[field]), (resp_fd['id'], resp_fd[field])))
                #d.append(resp_fd[field])
    if cpt > 3:
        print("I wait 1h")
        time.sleep(3)
        break
        
cpt

I wait 1h

4

In [35]:
print(diff)
for i in diff:
    print(i)
with open("others.json", "w") as outfile:
    json.dump(diff, outfile, indent=4)

{'extra_headers': [(('630177ae68501c3ed6f125c097af12402efcf757', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJb3IYkCRBK7hj4Ov3rIwAAdHIIAJJqxcODHCJU+sNKv3vP4uHv\ngffTacKaW1YpkrYgLSrzysASER4gjAeYysUQvVVGYYje5vP/xiiTaY4DGFHfwkSd\n/DoWeFNAlcUYANFrqgG3kfB+1vhSVV6E9WFuKbrRVRLBsSC5lbSOPGLp/0PxBBNw\nnypNqIR6k4k2TtmwsJoTDviJsd83O34EuloQKJF9eBNIj3GJ0GbREvh6SyvADg8l\nTO8M+L8yf/4FMYMutZgHSjkKJQEYEeFKUYjRIrPtaZRwQqhtBICbIBV3VFE1Rb2Y\nXrcukb7K3u9JaMPKAvN/F2ZxzYUAL8fKM9TZ9riH+NPlljHBtPVZbmP/gMpDUHs=\n=c1TB\n-----END PGP SIGNATURE-----\n']]), ('cf1b947d3268372107db02c6044304d1045b62d7', [])), (('630177ae68501c3ed6f125c097af12402efcf757', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJb3IYkCRBK7hj4Ov3rIwAAdHIIAJJqxcODHCJU+sNKv3vP4uHv\ngffTacKaW1YpkrYgLSrzysASER4gjAeYysUQvVVGYYje5vP/xiiTaY4DGFHfwkSd\n/DoWeFNAlcUYANFrqgG3kfB+1vhSVV6E9WFuKbrRVRLBsSC5lbSOPGLp/0PxBBNw\nnypNqIR6k4k2TtmwsJoTDviJsd83O34EuloQKJF9eBNIj3GJ0GbREvh6SyvADg8l\nTO8M+L8yf/4FMYMutZgHSjkKJQEYEeFKUYjRIrPtaZRwQqhtBICbIBV3VFE1Rb2Y\nXrcukb7K3u9JaMPKAvN/F2ZxzYUAL8fKM9TZ9riH+NPlljHBtPVZbmP/gMpDUHs=\n=c1TB\n-----END PGP SIGNATURE-----\n']]), ('cf1b947d3268372107db02c6044304d1045b62d7', [])), (('032b30e9e780531d64400b53d008dcf7d5245e73', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJcslPKCRBK7hj4Ov3rIwAAdHIIAIhZqK6VGBzx/OMTNEoJl7cO\neVgvLOG6PZsNKYjTFzZIBZk43tmY+c3Vk56zgLYHIHfT3O9qaBJ6NEWahBzKRech\nA0kXmrJKN99hoPHXaxaec38hvaWowxsMISugrptgqwW5RL/usmvRTM1qeWjBVw9v\nYcMAChGO6drk0qzWWv7ueJQUIPGl5qRf+E3LhxgjujRcwxo8KTTN+KEF4HFjrsSn\n3SxClBYq8RMxNl8Vn1Rjg7gNEzTJG4pN0k3KKQKD0ddIvuGo2vfrs+5CR2WAoSSP\niZd4r6988L1WxoX3ZmLz8WhyQuLz3Bt9ayotnokEwfrFzr6QzFQmn+MN2hQWy4M=\n=9Fk5\n-----END PGP SIGNATURE-----\n']]), ('891def9ca705e80be40af2d50c8499b5782bc8e6', [])), (('1749d929e836682aa34da9203d95813ef1a30daa', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJdzzmnCRBK7hj4Ov3rIwAAdHIIAE5mquwRPr1ijHAcffR2gL19\n8dhqGbfdg1dxTorI135Q8Qtk6MBGPsJNjITlv2SDvypHUCygAOBHISSEPmmjvr0H\nkB04e0uk3oJ/a1YA+XOV7ZcyOsc7rw4IXKmumTrQ+79dNds5zjmnQI+9ZQlpOOkZ\nrvrclF7uyHUno+lZnHieFkqlRlstDpDS8mWy974NYIeXU8bAfpjfwERkzPFQBZip\nCeoLcpGlFBNMq2ROFgBUsLXg5qQ0SUVxlnOv0+GhJlOBu0qtcIPpoR9+xuOlLNwh\nJjg0ufMByRRJfo/Ty/NORZnVEy9eH9gUQga3jTF23rrbltkz3JvtBVT9bfGbxow=\n=9DDb\n-----END PGP SIGNATURE-----\n']]), ('0179c2d82e68c8558c797dea43ae10c07cd6506f', [])), (('8f90585581fba29190c17701f014327fb8d18995', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\nVersion: GnuPG v2\n\niF4EABYIAAYFAlex7jEACgkQITLjp2bdf96PZQD+LzBtP/TkAK0hBRswXS8Mo560\nETqzuuRSnnBtDGFybeYA/00YvTgvQqMK2N6Vp5p/qp9IZw3f3XATZiWPQYWldaMP\n=dNGD\n-----END PGP SIGNATURE-----']]), ('920274facf7268c8c636a37e04124ae82dc19a8f', [])), (('39799f7564d28737fa815a3a5d370c91414998ef', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\nVersion: GnuPG v2\n\niQIcBAABCAAGBQJXvV4HAAoJEJHzszm5oCo9p8oQAKKn892JXnEZfR72j/87Sh5J\nVx0pVaq6qtaxNN5LnrjzqcKl1/d3aT6dD0sk8UsSd72vZYURmtZCpLAiYonL+rSf\nXFZM13SGwfjkIQse9gWyg84X+YQOCTI5kMhEL0MVwPLhMr/sp5GbPE0o4fh9BSkg\n2p8iZrfKRYa0e5PwD6avEZ3Sh90X0lZGN6DbMVahSHTaBvzRHqWZQCNHGsAR7TIq\nt9TlQ3jltD64KFVP7ySxwxvNhDk8n+koE53wxnbsTv2GXCDeM5zN5YJcrh5nW1/b\nN/J/WUyMkK0/MY2r03zrJHBFU3/+fyXqTHzfaLhpo5cq70SLq3PoYPfMvs4Bqpca\nH0ml70hPBHo6upy4olnLdFjfB8SC+EYmWDg1XRNRYTOpyiiwn9jN7YkvUcDEHk56\nQdkk2P34YdNet+JSrczguYIcAi9/t/pWkrcoKH6hjiweEv0kj8Dkrfpb9K2nZ6EG\nZXpgXzYEsOsOMiZ6tl9Qkhsl6bs3D58XdHV4a46YE0K6oiz4bvsEU013fL2DSmGc\n8padj4vhrnnqifrxSwUC3QjvkqRGlHpHRypdcov7RY9LSIs7fHgvjvWT8lqHs5fB\n9XFPhpJOKhCXPmxDCBd+tywDvA2b47swL58lnO7920ydBxd6CbeM3hHvEqXKxlN8\nIugEXQw5qXsS6wdmbJ8k\n=ErdV\n-----END PGP SIGNATURE-----']]), ('1162b22e7eb84a4329d9d655512e90d9aa510368', [])), (('4f319ced8015b8ce2552bab48a2d6f267ce2a430', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJb5Xi8CRBK7hj4Ov3rIwAAdHIIAHCsuJnpuIXJ6jMWrRlYr5I+\niGY6M2Lq8/7JrC1W90geGsTQ99wq6gCdks6xQQLV57slyAB+M7BbSm/sfvCEPTOQ\n6c92Fng+2DgbXPRUZjgc4xhvdkaRrT2UiJTmtn+JKmhtOqcl7iTNtBjlBwfNDSN2\nAHzTQzFPl9hr3fKInFmImQsqlumcMFI8kYEQv1d10hpAbjrUC71yLpp+1nU1cOZQ\n4OYPbnd4VhBvHcpl0nuZI+lNu4CazSdW4Rf9A5aEfSh2wu7xXOwbCMyxcTK8/w+4\ndfg9WL+Dt4OmkNiUmi9kviajM1goXwalMMetVDfENI3a5pT4ounReMpPhvef52k=\n=kerw\n-----END PGP SIGNATURE-----\n']]), ('0e8740c38b83e1ce1f5dacfff637cc1221865841', [])), (('4f319ced8015b8ce2552bab48a2d6f267ce2a430', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJb5Xi8CRBK7hj4Ov3rIwAAdHIIAHCsuJnpuIXJ6jMWrRlYr5I+\niGY6M2Lq8/7JrC1W90geGsTQ99wq6gCdks6xQQLV57slyAB+M7BbSm/sfvCEPTOQ\n6c92Fng+2DgbXPRUZjgc4xhvdkaRrT2UiJTmtn+JKmhtOqcl7iTNtBjlBwfNDSN2\nAHzTQzFPl9hr3fKInFmImQsqlumcMFI8kYEQv1d10hpAbjrUC71yLpp+1nU1cOZQ\n4OYPbnd4VhBvHcpl0nuZI+lNu4CazSdW4Rf9A5aEfSh2wu7xXOwbCMyxcTK8/w+4\ndfg9WL+Dt4OmkNiUmi9kviajM1goXwalMMetVDfENI3a5pT4ounReMpPhvef52k=\n=kerw\n-----END PGP SIGNATURE-----\n']]), ('0e8740c38b83e1ce1f5dacfff637cc1221865841', [])), (('e943896fc3a998627a8c5a8dec7336d65231a738', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJcofIUCRBK7hj4Ov3rIwAAdHIIADULw8rCMJfHUOWsUyGzJjWH\nXnHBj3QdeTcXEkaAEDt1s07pyaltWpCNeP9NQnzNZOt/GFqZcX5IutsMXY4/WXVJ\nhHqpipbCD9UmFcdHTKPljaS07Yv/h54AG9kMlhvlZgP+y5cvZlZVSp0AO20JscBT\nMQXOVvxrP2b6Jros0p5ONHjXc7/BMVNA2n/cUtuWaPxA6/mpLEMdfP8iiN6unpXH\nMN1rAIRTxfXtpFw/kxNvX9MA4Sno+iE9AjFxFvu1QRs/tei53/BKNzgMko/yGP4K\nfG5esH92DzemoymdSCNQvYL7YyiTjDgmK8d942l7am8IMJvDy04pwU37ROl1nDo=\n=DiN1\n-----END PGP SIGNATURE-----\n']]), ('249cf68e408d11c9ad1d542f750bff9ebfa962c1', [])), (('b74d1127f9f91fc1586a431150eee8f14009527d', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJdQ+Q0CRBK7hj4Ov3rIwAAdHIIAH2k8ov9gR9uWDVy46LqFo9p\nBil5U2v8fQcgDysRFatkQztsyZSQtvO1GSJ+Yw0apsrDmYY9FRjy2s8h9E3WHMLb\nriTCjgl5+vOt7yzMeN1VfM9YYNmnL7U7NwIEOo+1OiZouyY+DQDDHD1iPjfB88Ob\nPTt0szv3FJ49s94dOw1FkQ5kqZbxg7YfNDlsPYMfFwyU6mmjRL3mmxsld5VfaWzl\nuZ641/LsvxKv9N93dBF0S6i0ec6t99X/J+jix3PQfSpscGJbiW8MvubugUkMMMCU\nJnJQJ9rEhPJEFmu2gVZ02nSjgBwvtk801Epn5o0zNrRhcC3MDHOFN0GIzRSe1gg=\n=2QB9\n-----END PGP SIGNATURE-----\n']]), ('5a53ca835fcd6fe166840fb48e84f665cc2e5c40', [])), (('5b3f022b3d1f58c522af80645773439bda0478bd', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJc027jCRBK7hj4Ov3rIwAAdHIIADATI/p+u6Vo3eQV7lukQ89f\n3lx+cyaC8EF3cJs4R8s+yEQz24KcYxYS1LGGPOoTXGDHhH9dI/DPUwBSTYEpPeh3\njXRbeljcvqyZh0eUk+ekYZDT8OSE5SWkO5dU9vsZzk/lAmS7eJJ+XEXejMvweA3i\nO9C/5DqKRRV1UPBlhZ/qgr/37lGEcQD0R3lkdlxXpHqeUAJ8i/J/k6K1Oe3ey8vw\nnp3G4gG49JdHFXRg3tibUSFY/T3j4C4CGFaYX3TvlR5nOwVXAzJAtemYNRCRsUKo\nnro0D366Obx0NYEOd7p3JCOLYvvAH4/y7rpqwrg4BUZlCUmVy1AVfLc2O3RXElA=\n=bJn+\n-----END PGP SIGNATURE-----\n']]), ('22ba2ba56634a188f84987fab033c0e95aecaafe', [])), (('47bdde98c0f64e3dbe5145e1057e37afafb94bb2', []), ('90e444f989195d39942d8329b4b509f7a715967c', [['HG:rename-source', 'hg']])), (('fb7026d80bca47052177dd4e7c6d3759e787aba0', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJcMdwvCRBK7hj4Ov3rIwAAdHIIAACA1Qp0cegP4K+s19ChTtQz\n1MohK7sN6MzhF3HnElpTOl+nk5rwLlRqsQfCEiZQyJJw8stZ7SS5VJ+thddXL2ZO\nezpNY1oU+5X41Vg+473V3u4q6LmWfgPTv5ivcMjxNabH7QFQ/B9Is6Ue5XCBDuYi\nfEJz8bVj/+2IPZW2Q3D52wqZ3HvN2TaG60QNEt0shXiIaOpZKfgcUwe068yLf4Qa\nIV/B//Bd2riBueRU//ErvLZ60CVUp77Ro8/GuipFZ9t1d4J4h9wtmYhTW6dNftG5\npxmQQ+aDsMl2AIy9FV4kPcxWPaUZqfNKre6UceJwPg7a9v1cv7hEBvF+AJbwZT0=\n=WEiO\n-----END PGP SIGNATURE-----\n']]), ('10dfdd077d403cbbc0ed1a6ca7d0b327273f4791', [])), (('d12056c00876ed6de6d2609cf69ad43e3e9f5bfc', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJbG9RGCRBK7hj4Ov3rIwAAdHIIACWQ0UEsyJ55rs5S6JxDlRUy\nKdnhR1FkxfOaP4xUDQdVOkinpQtNay4pQNrejXUb0acOwIFGe8wHXGBGtANyuriO\nv2OO67sk6Mo8YKIaYWwyUZhL3+KVAYyHW5UNi6/1OBs5zuRA0nLQNPIv0N6E9S32\nX+w4zrO6vPuKHIwNo9pXJEekiBqXKhvl4gmqD2aWQjtkxaQkNW8nwjF0iJk1b2VI\nRfEdgO/HCtrXUl8DYgvcw90n4mfsDbkKAGdYPNl0vuVHzmCFSkaPTdRB16awPlnE\nfnIBDcRiZ5BErGPrl6+tRlgUnPR8UELxBLZ+aYTFdSpl+JZ5Mt0XNmrkIXA6U10=\n=agnJ\n-----END PGP SIGNATURE-----\n']]), ('1daf7e8092c4624830ac78659ae5b5cc3e49a4c3', [])), (('83756bab6165f0351feecdc5d6833d4765d32c55', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJcuyXYCRBK7hj4Ov3rIwAAdHIIAJtXcxPZxjvBWokVJ97kyAVi\nDjWRPBSudUxAutwBNSLn0KvRjqTtvUkRcftzijgtKoCi4iZZOxCJHu8vpQQ52ERK\nc1xMq4mWzS5MyBunNEboOvqW9pkGR3fMDhyZK09BVKp8wYh1bc3E8K42btz/GoUv\nSEFC0ZlpIZIO5Goijx8yV7xqnWyviY3IdUjqg/oF8w0vV44VpV9rpz7JsF6Na9Dg\nnGk3z8J3QSbTGYomWDWq7/Fdgi/KnCbvMH1dVOiVPMcdtISBwZnanTPxC6bWjs81\nLlkyKP6WTiDgv2mH+b5NasMMFnqio53UmaGxo79xzVEsIqPdtHNYRwHJ/EH90ns=\n=eji+\n-----END PGP SIGNATURE-----\n']]), ('ffd88798d30bef2197c7beaa5952799e7fc80ca7', [])), (('a5499b6cf883492ceaa97b3dcbf040ee8c7a3239', []), ('9d3a59554c2355d1a7e4b668bf10196b4e58ed7b', [['HG:rename-source', 'hg']])), (('a5499b6cf883492ceaa97b3dcbf040ee8c7a3239', []), ('9d3a59554c2355d1a7e4b668bf10196b4e58ed7b', [['HG:rename-source', 'hg']])), (('8a48eed3312d4edff0f0fad8a025ac010845ebed', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJZ951pCRBK7hj4Ov3rIwAAdHIIABqELjtwBC34HioLU14eZJsu\nzRqD4YaE/QwWGvQDeNFGV3bRNTWNOLm4Upx6YhWCX2r9IyDCqZ7QupoZ8ZWBMzw4\nJ2qaxkqgjou7Y29GBoZCs75f09fjEvFEg1ql4lPTmqi9zkn1xQ9FauCcMtN0Mszq\nXNuq04MpxFZrOOfFU967nRYiSw5lscNjLq+otsYjnCObK21QIZjFk2Cs0biwTRbg\nODyzWYepNUyJBf97YRS2CmswGTClshwqwa/v1eUA0OX9x9ELm7DxyXXBsONVXBRl\nAeEliuSLsFLH4oPCfP7qrtHdowfEr8naztTLNXj8+RUoMvQBfU9Bbud3ejbc/hI=\n=1j1q\n-----END PGP SIGNATURE-----\n']]), ('b0f095666448075d8dde571ee40d421e5246a44d', [])), (('8a48eed3312d4edff0f0fad8a025ac010845ebed', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJZ951pCRBK7hj4Ov3rIwAAdHIIABqELjtwBC34HioLU14eZJsu\nzRqD4YaE/QwWGvQDeNFGV3bRNTWNOLm4Upx6YhWCX2r9IyDCqZ7QupoZ8ZWBMzw4\nJ2qaxkqgjou7Y29GBoZCs75f09fjEvFEg1ql4lPTmqi9zkn1xQ9FauCcMtN0Mszq\nXNuq04MpxFZrOOfFU967nRYiSw5lscNjLq+otsYjnCObK21QIZjFk2Cs0biwTRbg\nODyzWYepNUyJBf97YRS2CmswGTClshwqwa/v1eUA0OX9x9ELm7DxyXXBsONVXBRl\nAeEliuSLsFLH4oPCfP7qrtHdowfEr8naztTLNXj8+RUoMvQBfU9Bbud3ejbc/hI=\n=1j1q\n-----END PGP SIGNATURE-----\n']]), ('b0f095666448075d8dde571ee40d421e5246a44d', [])), (('8364701164429ffc0717d09d846f324346b6afa5', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\niQEzBAABCAAdFiEEXdSi97DHPO8FJo5jImSXPBEV+OoFAl5d8qAACgkQImSXPBEV\n+Oocrwf9Gc3BSugoTjy9wipcJXrDb3r7vxJ//X2qgTTleHkBQ26Emcs3+Ow5Nn3l\nL2aGXdbpDXYyCi1VHXv98jb0ragZfjZo3jT7+Jcsdjn5iA3K7Q6L8131VK+TxoaH\nESBI8vyQgjIJVBhdxRLhbfnyfSW6Ru05hjTSYPlG5kql+KtftlDdPbnfi9Jffq7r\nBe0ti+pdfRBMKLOU9JS4R8NkadAJCr4HD7xfQ3xT/NWdAXG+PcFrdZ1O/974dC83\n9WmI7NQkyzqkBWMqwR3Js+hl5oLZMlN2RYiDMOlhIxsG0wcgMUCj5BSfGhPXryX+\nDrcnM32jjEaKadUz3yaJKjOsb1TQNw==\n=am0R\n-----END PGP SIGNATURE-----']]), ('e228f2794a029d8fba3867cf93115ab3d12d13ae', [])), (('ee680bdf3a436d7abc38a92c073df8a4e3dd2851', []), ('5d88cc6412c3ca9f3c4657f92a9fed2cafb4068d', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\nVersion: GnuPG v2\n\niF4EABYKAAYFAlcFA74ACgkQyy6wQqhQImrlYwD9HZM24TgAWH7V1gs7qxLQLqlV\nACI59G01y9k/0vIRq8QA/iyRw6EX0Gx5iFBpS+crA7xvdsnXnnqhOSsNEVn6LnsK\n=LwnB\n-----END PGP SIGNATURE-----']])), (('9a872a43cf605fffe074e00f393640dc944bcee7', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJdSeIuCRBK7hj4Ov3rIwAAdHIIAFs1+wGwAmSjcH5ruSaUUvJ4\nK/I2o3dJOhBy9B8UEgiJa0Kt5SGrfsty+CPLo9EXiADeNt8yhe5pbmJp+vOHORWV\nHZrgxZlq+Vdx1Tc7CME6+2dTS0VvXNrDL4Jg4hKc6U6tvIMi3o+jUY7pgwjZhShq\naTTsdV4M8mLgYNwYGGxuSkRk4PQ5fVfRF6WIzsX5YXJjTXqwD3gB99CIf3nM+lEm\nqZCDlcm1REsTi1qZbGhqvnhYymA6hr2wJNiKnYEnK9mt1tbASvKpy3HyO49j0PAm\nfDw6mnv/MMvUpjGfAgbR1poippAcMTwpXWmSe7suqntU8DgWln0rCzl3Whvt4us=\n=PVu8\n-----END PGP SIGNATURE-----\n']]), ('3a02d46a35c48dee8be63241bb25113dc7575897', [])), (('93c62c9b8a105e3f807a2baf17fa427d5776b980', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJdVThpCRBK7hj4Ov3rIwAAdHIIAHYAqriWm9/vkLOpUTAFOYve\n2TCpkilSSiOj8hl0hvo+DGzhGCzNJlxxkLk8yyTIXOwe46FpDAFU3qHcr5ePKQT1\njT9jEwasyI5Xtk9WAlPjot+P5iivfACMepm3NUJ1cG1r+GpsL9AVoVafYGXHyGA/\nX5eDDpOvnO++LsBo457xV2tqNAz4HiTK/4uID/SO/ppI7FHSy//OdMnlxaKskTky\nlQF4nId0lwGTfJTyzIVJsEM1ORXFDpWssB7/a2TjsPYE34r8cvdoFIF9vimTNre3\net9UD/EnbIPDTFTNXPonETjDLNKD8hczS6+R7gZGAkqJ2B0ImU60V6MVyONiMEw=\n=sntd\n-----END PGP SIGNATURE-----\n']]), ('6278e78ecca70b8b30db8b4e668b7be27c17e69b', [])), (('438652366290838621377be974dea59208b5e4a6', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJaAYxBCRBK7hj4Ov3rIwAAdHIIAE/8LD0Y7785KplovfYT+OhT\n+yC3tjEVxBhF32b1hd6F4JUDwSykdPv7Trr1DE1t8lyMBffM1+oo+NC+TiEG2K8H\n68dUUUO0X2O4NcSCYEh0HCEIGg/NB9D8EBKp0O6flSQ/toktrDq46oXWdj9Ta3XH\ntUovZzIBeQxsyACqThiwmlybfZCFf4k3tF86v8daKoWrSaRFPHLRYdzoXIocSWHn\nJC8TpApInhUj0Ed4WaSCtR8dwW8v/4e/fA9ITyvWCdtLEVbuoowJOm8wX7VsFdQq\nhxy7LPBT0tUMQVVR/fswIMFNP2otqdBWaSKnXYvPcm3BJVLkWisYQyS7RLk3N5M=\n=KM11\n-----END PGP SIGNATURE-----\n']]), ('01504599c3157ae939eb60b705ac80e3e8210aac', [])), (('438652366290838621377be974dea59208b5e4a6', [['gpgsig', '-----BEGIN PGP SIGNATURE-----\n\nwsBcBAABCAAQBQJaAYxBCRBK7hj4Ov3rIwAAdHIIAE/8LD0Y7785KplovfYT+OhT\n+yC3tjEVxBhF32b1hd6F4JUDwSykdPv7Trr1DE1t8lyMBffM1+oo+NC+TiEG2K8H\n68dUUUO0X2O4NcSCYEh0HCEIGg/NB9D8EBKp0O6flSQ/toktrDq46oXWdj9Ta3XH\ntUovZzIBeQxsyACqThiwmlybfZCFf4k3tF86v8daKoWrSaRFPHLRYdzoXIocSWHn\nJC8TpApInhUj0Ed4WaSCtR8dwW8v/4e/fA9ITyvWCdtLEVbuoowJOm8wX7VsFdQq\nhxy7LPBT0tUMQVVR/fswIMFNP2otqdBWaSKnXYvPcm3BJVLkWisYQyS7RLk3N5M=\n=KM11\n-----END PGP SIGNATURE-----\n']]), ('01504599c3157ae939eb60b705ac80e3e8210aac', []))], 'parents': [(('116d374be6eec196c51f1c00bf3d32c4f3cb20c1', [{'id': '88ad69a09c0d492dca12fbd1cff8555d99c2d25d', 'url': 'https://archive.softwareheritage.org/api/1/revision/88ad69a09c0d492dca12fbd1cff8555d99c2d25d/'}, {'id': '729d468239bd8f23ed4386fb4b15b85b1211a1e5', 'url': 'https://archive.softwareheritage.org/api/1/revision/729d468239bd8f23ed4386fb4b15b85b1211a1e5/'}]), ('dbbcd74539bf24367b4b76b419e2c30dbd5494de', [{'id': '729d468239bd8f23ed4386fb4b15b85b1211a1e5', 'url': 'https://archive.softwareheritage.org/api/1/revision/729d468239bd8f23ed4386fb4b15b85b1211a1e5/'}, {'id': '88ad69a09c0d492dca12fbd1cff8555d99c2d25d', 'url': 'https://archive.softwareheritage.org/api/1/revision/88ad69a09c0d492dca12fbd1cff8555d99c2d25d/'}]))]}
extra_headers
parents

In [13]:
resp = requests.get("https://archive.softwareheritage.org/api/1/stat/counters/", headers=headers)
counters = resp.json()
counters

{'origin': 301593525,
 'revision': 4179213822,
 'content': 19349187977,
 'directory': 15525483007,
 'release': 95109678,
 'person': 75679076,
 'snapshot': 283852050,
 'skipped_content': 336940,
 'origin_visit': 1521000675}