In [1]:
import os
import json
import pandas as pd
import numpy as np
import re
import random
import time
import pickle
pd.set_option('display.max_colwidth', None)

In [5]:
df = pd.read_pickle('res.pkl')

In [6]:
df.to_csv("res.csv", index=False)

In [2]:
prefix = "/home/infres/rapaport/results/FULL_2024_08/focus/classes"
class_files = os.listdir(prefix)
df = pd.DataFrame()
for file in class_files:
    df = pd.concat([df, pd.read_csv(prefix + "/" + file, delimiter=";")])

In [3]:
df.sample(5)

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories
255371,https://github.com/aws/amazon-vpc-cni-k8s,swh:1:snp:a9482fed401c040b370dc4fb509b6a5ff6ab17ef,refs/pull/1536/head,swh:1:rev:feeaba86a5235fc3b0f374eb2cd4039ef014fa27,swh:1:snp:51dea1dfd1ce922b40446b427efba6126c1a5cbc,NaN,DIR,",FileModified,FileRemoved"
123806,https://github.com/asciidoctor/asciidoctor-reveal.js,swh:1:snp:db676dbe5030eea52b868c2c7225bd60da709b97,refs/heads/renovate/major-all,swh:1:rev:d7280eebafb582e76e368b7ccd3ee038679c8ae6,swh:1:snp:5eb889685f400e428d18ee202bb6d34f18a5b7af,NaN,DIR,",FileModified"
156874,https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node.git,swh:1:snp:ed3e33ab01adf06e19eed33cf80303b1d7bb8706,refs/merge-requests/1409/merge,swh:1:rev:0b786bd7b35418a011667c34acf638963bcfdb13,swh:1:snp:69deae86f8ab9881661de674ffdb2c00c89a9492,NaN,DIR,",FileModified"
2830,https://github.com/mozilla-frontend-infra/bugzilla-graphql-gateway,swh:1:snp:80683f95586b3954b14b234d66eb59a22239a033,refs/heads/renovate/npm-snyk-vulnerability,swh:1:rev:31a2ba651c80fecdcdf354be05922aac841a3b57,swh:1:snp:1c42fcafc881e7750ffa2e6ff7e39d3341e6221a,NaN,DIR,",FileModified"
241720,https://github.com/HumanCellAtlas/data-browser,swh:1:snp:307a724d4a0863fcdb5fbb6bbb2951a7a3338d48,refs/heads/dependabot/npm_and_yarn/spa/types/gapi-0.0.41,swh:1:rev:4126926361b3be44632da0ec0c32b447b299c080,swh:1:snp:aa634785ec92177ac94b8eb229c7fca8a68ac1aa,NaN,DIR,",FileModified"

In [4]:
libwe = df.loc[df['origin']=="https://github.com/woodsts/libwebsockets"]

In [5]:
libwe

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories
9341,https://github.com/woodsts/libwebsockets,swh:1:snp:0daf9634bed22358dab68867335c357b0ea377e8,refs/heads/master,swh:1:rev:fd4614e1885b66a053827b42c1fa445f6bbe49af,swh:1:snp:75345312b6e211cf91e5d1c9afc5e392fe8b9a36,NaN,DIR,",FileModified"
11579,https://github.com/woodsts/libwebsockets,swh:1:snp:75345312b6e211cf91e5d1c9afc5e392fe8b9a36,refs/heads/master,swh:1:rev:02147ddb7c7c720f17a0dc6359b8cdb32778cf63,swh:1:snp:31d114802b75f43ee28b7a5e674175d5db9bd013,NaN,DIR,",FileModified"
57918,https://github.com/woodsts/libwebsockets,swh:1:snp:4e8fd2ee527247eaf79a7e9d8374bbffe013bc4f,refs/heads/master,swh:1:rev:72c854e02206d75d7a112429afb5ada086413c92,swh:1:snp:a0db2a3092a2dcc2da11fc13d16302b86a3c597f,NaN,DIR,",FileModified"
65408,https://github.com/woodsts/libwebsockets,swh:1:snp:ae675b82b8bd54f5e7121e9d7f4c930093c50ffe,refs/heads/main,swh:1:rev:5b224c913f84767c7ef945bcb3ee28d8b7a5e0db,swh:1:snp:dd0c4c9e5119bcfaafd46bcfaef1a78e5427a9c1,swh:1:rev:a5ea6eabca4164c98730fcb01af107fc7584bcf4,META,",CommitterDate,Message"
66665,https://github.com/woodsts/libwebsockets,swh:1:snp:797bc147d6745afc7f3417aafa87d7ca34e36553,refs/heads/main,swh:1:rev:41f8ea14a377ded29670a0a3338c6f385aa4adc2,swh:1:snp:c908ce41d97b757a90b10b39abec1b46518956d4,NaN,DIR,",FileModified"
67918,https://github.com/woodsts/libwebsockets,swh:1:snp:c908ce41d97b757a90b10b39abec1b46518956d4,refs/heads/main,swh:1:rev:f204a2332c18a90c30f27b9083face5bd3028811,swh:1:snp:f8ac1d78064c06cdb6e3ae82efbdb8f5be7c81a1,NaN,DIR,",FileModified"
69966,https://github.com/woodsts/libwebsockets,swh:1:snp:d50ea54f4ac85830d3698611df07f2e11a1c9b9f,refs/heads/main,swh:1:rev:71758536d758174b956969cd166249b617fe86b2,swh:1:snp:1d464a4dec720b0e53631f48530fd888aebdd1d2,NaN,DIR,",FileModified"
78461,https://github.com/woodsts/libwebsockets,swh:1:snp:3d700811d1bf4880ab8cccf188444b8ed082a652,HEAD,swh:1:rev:4f3d7f95e4df9f3c7e6df4ddf18836db5ed69028,swh:1:snp:0daf9634bed22358dab68867335c357b0ea377e8,NaN,DIR,",FileModified"
100790,https://github.com/woodsts/libwebsockets,swh:1:snp:c3201e79d30e16a27cb0a93592d60386821c69e7,refs/heads/main,swh:1:rev:5bcc5ac655b0656906ed92c432ff2d59b0da3dd2,swh:1:snp:b442fd263f354b44a3d1305ef2ea7b7f112b620b,NaN,DIR,",FileModified,FileRemoved"
103067,https://github.com/woodsts/libwebsockets,swh:1:snp:191169b2eb90180b8f742c7b267825c91276c5a9,HEAD,swh:1:rev:822824db68a712add6efa9506995940ea41e523c,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,NaN,DIR,",FileModified"
119482,https://github.com/woodsts/libwebsockets,swh:1:snp:c908ce41d97b757a90b10b39abec1b46518956d4,refs/heads/master,swh:1:rev:f204a2332c18a90c30f27b9083face5bd3028811,swh:1:snp:f8ac1d78064c06cdb6e3ae82efbdb8f5be7c81a1,NaN,DIR,",FileModified"
119974,https://github.com/woodsts/libwebsockets,swh:1:snp:bfeaec4236b43eeb4711f40a4dc9ff686979a763,refs/heads/main,swh:1:rev:4c98a545b5e4e88621ca5bff053ed39d832dc725,swh:1:snp:a8d61f5f76513180db6142151bdaca684e541c91,NaN,DIR,",FileModified"
120753,https://github.com/woodsts/libwebsockets,swh:1:snp:a8d61f5f76513180db6142151bdaca684e541c91,refs/heads/main,swh:1:rev:c85a33e21456bd222bfb076714fbadbd066bc8b5,swh:1:snp:071e1d7cfe0a021ae1382ac4d9422ffd1580808b,NaN,DIR,",FileModified"
124104,https://github.com/woodsts/libwebsockets,swh:1:snp:dffde56032c9b70bb131c51bf7e57e7f9a4f90aa,refs/heads/main,swh:1:rev:05d67c6e37897dcb02ec9d5d6d5d17387f1d2c39,swh:1:snp:876f59f9015508725413cde85d2c04e04a0b062d,NaN,DIR,",FileModified"
125765,https://github.com/woodsts/libwebsockets,swh:1:snp:876f59f9015508725413cde85d2c04e04a0b062d,refs/heads/main,swh:1:rev:96a548ca96a1f06f2ef526c4fb8e4f3eb7c578d2,swh:1:snp:1207deae0dbf3fe7f429dbddd70fe57aca9d5ca5,NaN,DIR,",FileModified"
156053,https://github.com/woodsts/libwebsockets,swh:1:snp:bbb74c39184668f2fe32e0570da962b0d2f33a3f,HEAD,swh:1:rev:7191323baeeecf680fb5b0145cdfdcaf322bbe85,swh:1:snp:9195b3967c156bf52cd261e0325343028f4e39b4,NaN,DIR,",FileModified"
156227,https://github.com/woodsts/libwebsockets,swh:1:snp:797bc147d6745afc7f3417aafa87d7ca34e36553,refs/heads/master,swh:1:rev:41f8ea14a377ded29670a0a3338c6f385aa4adc2,swh:1:snp:c908ce41d97b757a90b10b39abec1b46518956d4,NaN,DIR,",FileModified"
172487,https://github.com/woodsts/libwebsockets,swh:1:snp:4e8fd2ee527247eaf79a7e9d8374bbffe013bc4f,refs/heads/v1.7-stable,swh:1:rev:e680ba7ead731a9f012b1851df7d2f69ee5c45f9,swh:1:snp:a0db2a3092a2dcc2da11fc13d16302b86a3c597f,NaN,DIR,",FileModified"
184482,https://github.com/woodsts/libwebsockets,swh:1:snp:c7b261fc971ee9152446766fb948d73b52109282,refs/heads/main,swh:1:rev:5ff8e447eb0f02a80cf757b2ed20a6f15864b5ff,swh:1:snp:dffde56032c9b70bb131c51bf7e57e7f9a4f90aa,NaN,DIR,",FileModified"
186023,https://github.com/woodsts/libwebsockets,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,HEAD,swh:1:rev:1672a44b386611a3fa4394e74b73c3ce4a5a84c0,swh:1:snp:6208eda264baaa56b982af5296fa0e70f4a37a02,NaN,DIR,",FileModified"
215433,https://github.com/woodsts/libwebsockets,swh:1:snp:05c0a347f9e6f40e443a1fe4ec6c9d6962ed1774,HEAD,swh:1:rev:cd8f9bce32332e229e289764504482012c78d2ee,swh:1:snp:346fe8093f6a8cfdb77b90d526f0e65619994366,NaN,DIR,",FileModified,FileRemoved"
216532,https://github.com/woodsts/libwebsockets,swh:1:snp:80e3dd68272871266ca5fb538f0a5aebccb3581f,refs/heads/main,swh:1:rev:76355f7270537a8778fb430de6183f70cfc6f79a,swh:1:snp:c7b261fc971ee9152446766fb948d73b52109282,NaN,DIR,",FileModified"
218608,https://github.com/woodsts/libwebsockets,swh:1:snp:4e8fd2ee527247eaf79a7e9d8374bbffe013bc4f,HEAD,swh:1:rev:72c854e02206d75d7a112429afb5ada086413c92,swh:1:snp:a0db2a3092a2dcc2da11fc13d16302b86a3c597f,NaN,DIR,",FileModified"
222756,https://github.com/woodsts/libwebsockets,swh:1:snp:cd41a2b7c46dfb73ac8ddfd909da77f752809880,refs/heads/main,swh:1:rev:86d9d44da0d61d6dac496be9b6df11f3e009e26e,swh:1:snp:bfeaec4236b43eeb4711f40a4dc9ff686979a763,NaN,DIR,",FileModified"
229917,https://github.com/woodsts/libwebsockets,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,refs/heads/v2.1-stable,swh:1:rev:1cc34f22e85ff20634deb2b7497253a55a123b97,swh:1:snp:6208eda264baaa56b982af5296fa0e70f4a37a02,NaN,DIR,",FileModified"
243855,https://github.com/woodsts/libwebsockets,swh:1:snp:bbb74c39184668f2fe32e0570da962b0d2f33a3f,refs/heads/master,swh:1:rev:7191323baeeecf680fb5b0145cdfdcaf322bbe85,swh:1:snp:9195b3967c156bf52cd261e0325343028f4e39b4,NaN,DIR,",FileModified"
266012,https://github.com/woodsts/libwebsockets,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,refs/heads/v2.0-stable,swh:1:rev:9f648e595a6077bb06b8d2f5a1b917eb563705cc,swh:1:snp:6208eda264baaa56b982af5296fa0e70f4a37a02,NaN,DIR,",FileModified"
266751,https://github.com/woodsts/libwebsockets,swh:1:snp:0daf9634bed22358dab68867335c357b0ea377e8,HEAD,swh:1:rev:fd4614e1885b66a053827b42c1fa445f6bbe49af,swh:1:snp:75345312b6e211cf91e5d1c9afc5e392fe8b9a36,NaN,DIR,",FileModified"
277498,https://github.com/woodsts/libwebsockets,swh:1:snp:0daf9634bed22358dab68867335c357b0ea377e8,refs/heads/v2.0-stable,swh:1:rev:29bb33bd81a9ee045a77ebaeff861a800026c71b,swh:1:snp:75345312b6e211cf91e5d1c9afc5e392fe8b9a36,NaN,DIR,",FileModified"
280887,https://github.com/woodsts/libwebsockets,swh:1:snp:d4a356fd02cfacc9a3bc51579bc383537b9215cb,refs/heads/master,swh:1:rev:d34e21793bbd2d03538533c97a2c89e678321929,swh:1:snp:5e34d3a472f810485afda34cbe1e5bd89191978a,NaN,DIR,",FileModified"
290681,https://github.com/woodsts/libwebsockets,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,refs/heads/master,swh:1:rev:1672a44b386611a3fa4394e74b73c3ce4a5a84c0,swh:1:snp:6208eda264baaa56b982af5296fa0e70f4a37a02,NaN,DIR,",FileModified"
291694,https://github.com/woodsts/libwebsockets,swh:1:snp:58e1bd571cf4dfb525332394581d293052ba6e78,refs/heads/esp32,swh:1:rev:f9ed753968704850cf8c64e23ffc0fdb0dbe8626,swh:1:snp:2a9d86920328eb43f45eb7094e60df75df9c6551,NaN,DIR,",ContentSplit"
306663,https://github.com/woodsts/libwebsockets,swh:1:snp:f8ac1d78064c06cdb6e3ae82efbdb8f5be7c81a1,refs/heads/main,swh:1:rev:077bba9c2e21ed5ee6fa29203165b5ca6ee590a9,swh:1:snp:cd41a2b7c46dfb73ac8ddfd909da77f752809880,NaN,DIR,",FileModified"
324353,https://github.com/woodsts/libwebsockets,swh:1:snp:6208eda264baaa56b982af5296fa0e70f4a37a02,refs/heads/temp,swh:1:rev:1728988efa97aefdcf6c4feb06877e460880cda2,swh:1:snp:05c0a347f9e6f40e443a1fe4ec6c9d6962ed1774,NaN,DIR,",FileModified"
364244,https://github.com/woodsts/libwebsockets,swh:1:snp:75345312b6e211cf91e5d1c9afc5e392fe8b9a36,HEAD,swh:1:rev:02147ddb7c7c720f17a0dc6359b8cdb32778cf63,swh:1:snp:31d114802b75f43ee28b7a5e674175d5db9bd013,NaN,DIR,",FileModified"
377894,https://github.com/woodsts/libwebsockets,swh:1:snp:346fe8093f6a8cfdb77b90d526f0e65619994366,HEAD,swh:1:rev:98736503b08af23de731888c0a28ddafd499cad3,swh:1:snp:3c38c10a0f9420a3f8379686b1fb1bd06b216874,NaN,DIR,",FileModified"
387504,https://github.com/woodsts/libwebsockets,swh:1:snp:5e34d3a472f810485afda34cbe1e5bd89191978a,HEAD,swh:1:rev:3d3848e81cfd2fe487b15c5e484ff569bea0a03b,swh:1:snp:bbb74c39184668f2fe32e0570da962b0d2f33a3f,NaN,DIR,",FileModified"
389566,https://github.com/woodsts/libwebsockets,swh:1:snp:191169b2eb90180b8f742c7b267825c91276c5a9,refs/heads/master,swh:1:rev:822824db68a712add6efa9506995940ea41e523c,swh:1:snp:e1f66ad2a7f4fc5bd034f70d9e0c794e828d2f36,NaN,DIR,",FileModified"
398920,https://github.com/woodsts/libwebsockets,swh:1:snp:05c0a347f9e6f40e443a1fe4ec6c9d6962ed1774,refs/heads/master,swh:1:rev:cd8f9bce32332e229e289764504482012c78d2ee,swh:1:snp:346fe8093f6a8cfdb77b90d526f0e65619994366,NaN,DIR,",FileRemoved,FileModified"
407784,https://github.com/woodsts/libwebsockets,swh:1:snp:d4a356fd02cfacc9a3bc51579bc383537b9215cb,HEAD,swh:1:rev:d34e21793bbd2d03538533c97a2c89e678321929,swh:1:snp:5e34d3a472f810485afda34cbe1e5bd89191978a,NaN,DIR,",FileModified"
416609,https://github.com/woodsts/libwebsockets,swh:1:snp:3d700811d1bf4880ab8cccf188444b8ed082a652,refs/heads/master,swh:1:rev:4f3d7f95e4df9f3c7e6df4ddf18836db5ed69028,swh:1:snp:0daf9634bed22358dab68867335c357b0ea377e8,NaN,DIR,",FileModified"
418609,https://github.com/woodsts/libwebsockets,swh:1:snp:071e1d7cfe0a021ae1382ac4d9422ffd1580808b,refs/heads/main,swh:1:rev:0b8ba7672aa25492234c9ccea0afbf6917b2b2e5,swh:1:snp:80e3dd68272871266ca5fb538f0a5aebccb3581f,NaN,DIR,",FileModified"
424001,https://github.com/woodsts/libwebsockets,swh:1:snp:5e34d3a472f810485afda34cbe1e5bd89191978a,refs/heads/master,swh:1:rev:3d3848e81cfd2fe487b15c5e484ff569bea0a03b,swh:1:snp:bbb74c39184668f2fe32e0570da962b0d2f33a3f,NaN,DIR,",FileModified"
426507,https://github.com/woodsts/libwebsockets,swh:1:snp:346fe8093f6a8cfdb77b90d526f0e65619994366,refs/heads/master,swh:1:rev:98736503b08af23de731888c0a28ddafd499cad3,swh:1:snp:3c38c10a0f9420a3f8379686b1fb1bd06b216874,NaN,DIR,",FileModified"

In [10]:
orig_count = df['origin'].value_counts().reset_index()

In [13]:
orig_count.loc[orig_count['count'].apply(lambda x: x > 3 and x < 5)].head()

                                           origin  count
204991           https://github.com/o68x/FaireBnb      4
204992  https://github.com/shr-project/meta-clang      4
204993           https://github.com/kyredyrf/test      4
204994           https://github.com/moldyn/MoSAIC      4
204995    https://github.com/murashki/my-test-app      4

In [18]:
df.loc[df['origin']=="https://github.com/shr-project/meta-clang"]

,origin,snapshot_src,branch_name,missing_commit,snapshot_dst,first_difference,main_category,sub_categories
286144,https://github.com/shr-project/meta-clang,swh:1:snp:60119e178201e4d26da7f68421a322a821ce16b9,refs/heads/jansa/langdale,swh:1:rev:69380826d2ed5d58bc32abe94170cdfb4a12f7ca,swh:1:snp:6bd8602fd85a4550fddd7eae5060f6666fad7b44,swh:1:rev:366ad9356c3e982c51350773e3c9e7f7b2ff0bab,META,",CommitterDate,Committer"
345881,https://github.com/shr-project/meta-clang,swh:1:snp:6b007923b2e3025f3e674b3157b1e10f44876f4b,refs/heads/jansa/master,swh:1:rev:56f5d77e6c313dac88104d7db43b910ea4495582,swh:1:snp:d7f1af61901533da7dd9dc19502b87d375b777e6,NaN,DIR,",FileModified"
347290,https://github.com/shr-project/meta-clang,swh:1:snp:4e915b657f2f6ca32ceac7fa721c4e389622a6b5,refs/heads/jansa/langdale,swh:1:rev:fc9c05a33061d4185d17be90c6604e817b51f3ac,swh:1:snp:d15faffd6532a396274da49d02bb00d9b200ff87,swh:1:rev:fc9c05a33061d4185d17be90c6604e817b51f3ac,DIR,",DifferentBranchName"
348704,https://github.com/shr-project/meta-clang,swh:1:snp:936e5733f75f7d7c2f2fb98f2cd4da42c846d5f1,refs/heads/jansa/master,swh:1:rev:bc839177ad165da31006873ca860b08139683834,swh:1:snp:8e58721b1d60590d03d8c28868a536181593c2b4,NaN,DIR,",FileRemoved,FileModified"